package com.ecopic.entity;
// Generated Oct 18, 2022, 3:29:14 AM by Hibernate Tools 5.6.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "ecopic")
@NamedQueries({
	@NamedQuery(name="Category.findAll", query = "SELECT c FROM Category c ORDER BY c.name"),
	@NamedQuery(name="Category.findByName", query = "SELECT c FROM Category c WHERE c.name = :name"),
	@NamedQuery(name="Category.countAll", query = "SELECT Count(*) From Category"),
})
public class Category implements java.io.Serializable {

	private Integer categoryId;
	private String name;
	private Set<Picture> pictures = new HashSet<Picture>(0);

	public Category() {
	}

	public Category(String name) {
		this.name = name;
	}
	public Category(Integer id, String name) {
		this(name);
		this.categoryId = id;
	}
	


	public Category(String name, Set<Picture> pictures) {
		this.name = name;
		this.pictures = pictures;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "category_id", unique = true, nullable = false)
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set<Picture> getPictures() {
		return this.pictures;
	}

	public void setPictures(Set<Picture> pictures) {
		this.pictures = pictures;
	}

}

