package com.ecopic.entity;
// Generated Nov 10, 2022, 11:48:06 PM by Hibernate Tools 5.2.13.Final

import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * OrderDetailId generated by hbm2java
 */
@Embeddable
public class OrderDetailId implements java.io.Serializable {

	private Picture picture;
	private PictureOrder pictureOrder;
	
	public OrderDetailId() {
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "picture_id", insertable = false, updatable = false, nullable = false)
	public Picture getPicture() {
		return this.picture;
	}

	public void setPicture(Picture picture) {
		this.picture = picture;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", insertable = false, updatable = false, nullable = false)
	public PictureOrder getPictureOrder() {
		return this.pictureOrder;
	}

	public void setPictureOrder(PictureOrder pictureOrder) {
		this.pictureOrder = pictureOrder;
	}

	@Override
	public int hashCode() {
		return Objects.hash(picture, pictureOrder);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		OrderDetailId other = (OrderDetailId) obj;
		return Objects.equals(picture, other.picture) && Objects.equals(pictureOrder, other.pictureOrder);
	}
	
	
}
