package com.ecopic.entity;
// Generated Nov 10, 2022, 11:48:06 PM by Hibernate Tools 5.2.13.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

import com.ecopic.entity.Picture;

/**
 * OrderDetail generated by hbm2java
 */
@Entity
@Table(name = "order_detail", catalog = "ecopic")
@NamedQueries({
	@NamedQuery(name="OrderDetail.bestSelling",query = "SELECT od.picture FROM OrderDetail od GROUP by od.picture.pictureId "
			+ "ORDER BY SUM(od.quantity) DESC"),
})
public class OrderDetail implements java.io.Serializable {

	private OrderDetailId id =  new OrderDetailId();
	private Picture picture;
	private PictureOrder pictureOrder;
	private int quantity;
	private float subtotal;

	public OrderDetail() {
	}

	public OrderDetail(OrderDetailId id) {
		this.id = id;
	}

	public OrderDetail(OrderDetailId id, Picture picture, PictureOrder pictureOrder,int quantity, float subtotal) {
		this.id = id;
		this.picture = picture;
		this.pictureOrder = pictureOrder;
		this.quantity = quantity;
		this.subtotal = subtotal;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "orderId", column = @Column(name = "order_id", nullable = false)),
			@AttributeOverride(name = "pictureId", column = @Column(name = "picture_id", nullable = false))})
	public OrderDetailId getId() {
		return this.id;
	}

	public void setId(OrderDetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "picture_id", insertable = false, updatable = false, nullable = false)
	public Picture getPicture() {
		return this.picture;
	}

	public void setPicture(Picture picture) {
		this.picture = picture;
		this.id.setPicture(picture);
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", insertable = false, updatable = false, nullable = false)
	public PictureOrder getPictureOrder() {
		return this.pictureOrder;
	}

	public void setPictureOrder(PictureOrder pictureOrder) {
		this.pictureOrder = pictureOrder;
		this.id.setPictureOrder(pictureOrder);
	}
	
	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "subtotal", nullable = false, precision = 12, scale = 0)
	public float getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(float subtotal) {
		this.subtotal = subtotal;
	}

}
