	package com.ecopic.entity;
// Generated Oct 30, 2022, 1:32:48 PM by Hibernate Tools 5.2.13.Final

import java.util.Base64;
import java.util.Comparator;
import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;


/**
 * Picture generated by hbm2java
 */
@Entity
@Table(name = "picture", catalog = "ecopic", uniqueConstraints = @UniqueConstraint(columnNames = "title"))
@NamedQueries({
	@NamedQuery(name="Picture.findAll",query="SELECT p FROM Picture p"),
	@NamedQuery(name="Picture.findByTitle",query="SELECT p FROM Picture p WHERE p.title = :title"),
	@NamedQuery(name="Picture.countAll",query="SELECT COUNT(*) FROM Picture p"),
	@NamedQuery(name="Picture.search",query="SELECT p FROM Picture p WHERE p.title LIKE '%' || :keyword || '%'"
			+ " OR p.author LIKE '%' || :keyword || '%'"
			+ " OR p.description LIKE '%' || :keyword || '%'"),
	@NamedQuery(name="Picture.listNew",query="SELECT p FROM Picture p ORDER BY p.publishDate DESC"),
	@NamedQuery(name="Picture.countByCategory",query="SELECT COUNT(p) FROM Picture p "
			+ "WHERE p.category.categoryId = :catId"),
	@NamedQuery(name="Picture.findByCategory",query="SELECT p FROM Picture p JOIN "
			+ "Category c ON p.category.categoryId = c.categoryId AND c.categoryId = :catId"),
})
public class Picture implements java.io.Serializable {

	@Override
	public int hashCode() {
		return Objects.hash(pictureId);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Picture other = (Picture) obj;
		return Objects.equals(pictureId, other.pictureId);
	}
	
	private Integer pictureId;
	private Category category;
	private String title;
	private String author;
	private String description;
	private byte[] image;
	private String base64Image;
	private float price;
	private Date publishDate;
	private Date lastUpdateTime;
	private Set<Review> reviews = new HashSet<Review>(0);
	private Set<OrderDetail> oderDetails = new HashSet<OrderDetail>(0);

	public Picture() {
	}

	public Picture(Integer pictureId) {
		super();
		this.pictureId = pictureId;
	}

	public Picture(Category category, String title, String author, String description, byte[] image, float price,
			Date publishDate, Date lastUpdateTime) {
		this.category = category;
		this.title = title;
		this.author = author;
		this.description = description;
		this.image = image;
		this.price = price;
		this.publishDate = publishDate;
		this.lastUpdateTime = lastUpdateTime;
	}

	public Picture(Category category, String title, String author, String description, byte[] image, float price,
			Date publishDate, Date lastUpdateTime, Set<Review> reviews, Set<OrderDetail> oderDetails) {
		this.category = category;
		this.title = title;
		this.author = author;
		this.description = description;
		this.image = image;
		this.price = price;
		this.publishDate = publishDate;
		this.lastUpdateTime = lastUpdateTime;
		this.reviews = reviews;
		this.oderDetails = oderDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "picture_id", unique = true, nullable = false)
	public Integer getPictureId() {
		return this.pictureId;
	}

	public void setPictureId(Integer pictureId) {
		this.pictureId = pictureId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "category_id", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "title", unique = true, nullable = false, length = 128)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "author", nullable = false, length = 64)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "description", nullable = false, length = 16777215)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "image", nullable = false)
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	@Column(name = "price", nullable = false, precision = 12, scale = 0)
	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "publish_date", nullable = false, length = 10)
	public Date getPublishDate() {
		return this.publishDate;
	}

	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update_time", nullable = false, length = 19)
	public Date getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "picture")
	public Set<Review> getReviews() {
		TreeSet<Review> sortedReviews = new TreeSet<Review>(new Comparator<Review>() {

			@Override
			public int compare(Review review1, Review review2) {
				return review2.getReviewTime().compareTo(review1.getReviewTime());
			}
			
		});
		
		sortedReviews.addAll(reviews);
		return sortedReviews;
	}

	public void setReviews(Set<Review> reviews) {
		this.reviews = reviews;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "picture")
	public Set<OrderDetail> getOderDetails() {
		return this.oderDetails;
	}

	public void setOderDetails(Set<OrderDetail> oderDetails) {
		this.oderDetails = oderDetails;
	}
	
	@javax.persistence.Transient
	public String getBase64Image() {
		this.base64Image = Base64.getEncoder().encodeToString(this.image);
		return this.base64Image;
	}
	@javax.persistence.Transient
	public void setBase64Image(String base64Image) {
		this.base64Image = base64Image;
	}
	
	@javax.persistence.Transient
	public float getAverageRating() {
		float averageRating = 0.0f;
		float sum = 0.0f;
		
		if(reviews.isEmpty()) {
			return 0.0f;
		}
		
		for(Review review : reviews) {
			sum+=review.getRating();
		}
		
		averageRating = sum / reviews.size();
		
		return averageRating;
	}
	@javax.persistence.Transient
	public String getRatingStars() {
		float averageRating = getAverageRating();
		
		return getRatingString(averageRating);
	}
	
	@javax.persistence.Transient
	public String getRatingString(float averageRating) {
		String result = "";
		
		int numberOfStarsOn = (int) averageRating;
		
		for(int i = 1; i <= numberOfStarsOn; i++) {
			result += "on,";
		}
		
		int next = numberOfStarsOn + 1;
		
		if(averageRating > numberOfStarsOn) {
			result +="half,";
			next++;
		}
		
		for(int j = next; j <= 5; j++) {
			result += "off,";
		}
		
		return result.substring(0,result.length()-1);
	}
}
