package com.ecopic.entity;
// Generated Oct 30, 2022, 1:32:48 PM by Hibernate Tools 5.2.13.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Review generated by hbm2java
 */
@Entity
@Table(name = "review", catalog = "ecopic")
@NamedQueries({
	@NamedQuery(name ="Review.listAll", query="SELECT r FROM Review r ORDER BY r.reviewTime DESC"),
	@NamedQuery(name ="Review.countAll", query="SELECT COUNT(r) FROM Review r"),
	@NamedQuery(name ="Review.mostFavoredPictures", 
		query="SELECT r.picture, COUNT(r.picture.pictureId) AS ReviewCount, AVG(r.rating) as AvgRating "
			+ "FROM Review r GROUP BY r.picture.pictureId HAVING AVG(r.rating) >= 4.0"
			+ "ORDER BY ReviewCount DESC, AvgRating DESC"),
	@NamedQuery(name ="Review.findByCustomerAndPicture", query="SELECT r FROM Review r "
			+ "WHERE r.customer.customerId = :customerId "
			+ " AND r.picture.pictureId = :pictureId"),
})
public class Review implements java.io.Serializable {

	private Integer reviewId;
	private Customer customer;
	private Picture picture;
	private int rating;
	private String headline;
	private String comment;
	private Date reviewTime;

	public Review() {
	}

	public Review(Customer customer, Picture picture, int rating, String headline, String comment, Date reviewTime) {
		this.customer = customer;
		this.picture = picture;
		this.rating = rating;
		this.headline = headline;
		this.comment = comment;
		this.reviewTime = reviewTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "review_id", unique = true, nullable = false)
	public Integer getReviewId() {
		return this.reviewId;
	}

	public void setReviewId(Integer reviewId) {
		this.reviewId = reviewId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "picture_id", nullable = false)
	public Picture getPicture() {
		return this.picture;
	}

	public void setPicture(Picture picture) {
		this.picture = picture;
	}

	@Column(name = "rating", nullable = false)
	public int getRating() {
		return this.rating;
	}

	public void setRating(int rating) {
		this.rating = rating;
	}

	@Column(name = "headline", nullable = false, length = 128)
	public String getHeadline() {
		return this.headline;
	}

	public void setHeadline(String headline) {
		this.headline = headline;
	}

	@Column(name = "comment", nullable = false, length = 500)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "review_time", nullable = false, length = 19)
	public Date getReviewTime() {
		return this.reviewTime;
	}

	public void setReviewTime(Date reviewTime) {
		this.reviewTime = reviewTime;
	}
	
	@javax.persistence.Transient
	public String getStars() {
		String result = "";
		
		int numberOfStarsOn = (int) rating;
		
		for(int i = 1; i <= numberOfStarsOn; i++) {
			result += "on,";
		}
		
		int next = numberOfStarsOn + 1;
		
		for(int j = numberOfStarsOn + 1	; j <= 5; j++) {
			result += "off,";
		}
		
		return result.substring(0,result.length()-1);
	}

}
